language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install pep8 --use-mirrors"
before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 *.py"
  - "pep8 --show-source --exclude=migrations  --ignore=E501 ."
# command to run tests
script:
  - python manage.py test blog
